name: Other-Test
  
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2.3.4
        with:
          path: repo
      - name: Test
        run: echo ((Get-Item .).FullName)
        working-directory: repo
      - name: Test2
        run: echo ((Get-Item .).FullName)
      - name: Test5
        run: echo ((Get-Item .).FullName)
        working-directory: repo/Synapse
      - name: Test6
        run: echo ((Get-Item .).FullName)
      - name: Test3
        run: echo ((Get-Item .).FullName)
        working-directory: repo\Synapse
      - name: Test4
        run: echo ((Get-Item .).FullName)
